-- =============================================
-- Espina Bífida de Nuevo León - Caballos del Castillo
-- Oracle SQL Compatible
-- =============================================

SELECT DBMS_METADATA.GET_DDL('TABLE', table_name) 
FROM user_tables;


-- USUARIOS
CREATE TABLE "ADMIN"."USUARIOS" 
   (	"ID_USUARIO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CORREO" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"PASSWORD_HASH" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"ROL" VARCHAR2(20 BYTE), 
	"FECHA_CREACION" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"ACTIVO" NUMBER(1,0), 
	"PROVIDER" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"APELLIDOS" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."USUARIOS" ADD CHECK (activo IN (0,1)) ENABLE;
ALTER TABLE "ADMIN"."USUARIOS" ADD PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."USUARIOS" ADD UNIQUE ("CORREO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."USUARIOS" ADD CONSTRAINT "CHK_USUARIOS_ROL" CHECK (ROL IN ('admin', 'medico', 'finanzas', 'not assigned')) ENABLE;

-- ASOCIADOS
CREATE TABLE "ADMIN"."ASOCIADO" 
   (	"ID_ASOCIADO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_CREDENCIAL" NUMBER, 
	"NUMERO_ID" NUMBER, 
	"CURP" VARCHAR2(18 BYTE), 
	"FECHA_ALTA" DATE, 
	"ESTATUS" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"VIGENCIA_DESDE" DATE, 
	"VIGENCIA_HASTA" DATE, 
	"APELLIDOS" VARCHAR2(200 BYTE), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"ACTIVO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."ASOCIADO" ADD PRIMARY KEY ("ID_ASOCIADO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."ASOCIADO" ADD UNIQUE ("NUMERO_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."ASOCIADO" ADD UNIQUE ("CURP")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."ASOCIADO" ADD CONSTRAINT "CHK_ASOCIADO_ESTATUS" CHECK (estatus IN ('pendiente','confirmado','rechazado')) ENABLE;
ALTER TABLE "ADMIN"."ASOCIADO" ADD CONSTRAINT "CHK_ACT_ASC" CHECK (activo in ('Activo', 'Inactivo', 'Pendiente')) ENABLE;
ALTER TABLE "ADMIN"."ASOCIADO" ADD CONSTRAINT "FK_ASOCIADO_CREDENCIAL" FOREIGN KEY ("ID_CREDENCIAL")
	  REFERENCES "ADMIN"."CREDENCIAL" ("ID_CREDENCIAL") ENABLE;

-- SOLICITUD
CREATE TABLE "ADMIN"."SOLICITUD" 
   (	"ID_SOLICITUD" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_ASOCIADO" NUMBER, 
	"ORIGEN" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"FECHA_SOLICITUD" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."SOLICITUD" ADD PRIMARY KEY ("ID_SOLICITUD")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."SOLICITUD" ADD UNIQUE ("ID_ASOCIADO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."SOLICITUD" ADD CONSTRAINT "CHK_SOLICITUD_ORIGEN" CHECK (origen IN ('web','presencial')) ENABLE;
ALTER TABLE "ADMIN"."SOLICITUD" ADD CONSTRAINT "FK_SOLICITUD_ASOCIADO" FOREIGN KEY ("ID_ASOCIADO")
	  REFERENCES "ADMIN"."ASOCIADO" ("ID_ASOCIADO") ENABLE;

-- DIRECCION
CREATE TABLE "ADMIN"."DIRECCION" 
   (	"ID_DIRECCION" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CALLE" VARCHAR2(200 BYTE), 
	"CIUDAD" VARCHAR2(100 BYTE), 
	"ESTADO" VARCHAR2(100 BYTE), 
	"CP" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."DIRECCION" ADD PRIMARY KEY ("ID_DIRECCION")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;

-- ASOCIADO_DIRECCION
CREATE TABLE "ADMIN"."ASOCIADO_DIRECCION" 
   (	"ID_ASOCIADO" NUMBER NOT NULL ENABLE, 
	"ID_DIRECCION" NUMBER NOT NULL ENABLE, 
	"TIPO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."ASOCIADO_DIRECCION" ADD CONSTRAINT "PK_ASOCIADO_DIRECCION" PRIMARY KEY ("ID_ASOCIADO", "ID_DIRECCION")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."ASOCIADO_DIRECCION" ADD CONSTRAINT "CHK_ASODIR_TIPO" CHECK (tipo IN ('principal','emergencia')) ENABLE;
ALTER TABLE "ADMIN"."ASOCIADO_DIRECCION" ADD CONSTRAINT "FK_ASODIR_ASOCIADO" FOREIGN KEY ("ID_ASOCIADO")
	  REFERENCES "ADMIN"."ASOCIADO" ("ID_ASOCIADO") ENABLE;
ALTER TABLE "ADMIN"."ASOCIADO_DIRECCION" ADD CONSTRAINT "FK_ASODIR_DIRECCION" FOREIGN KEY ("ID_DIRECCION")
	  REFERENCES "ADMIN"."DIRECCION" ("ID_DIRECCION") ENABLE;

-- TELEFONO
CREATE TABLE "ADMIN"."TELEFONO" 
   (	"ID_TELEFONO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_ASOCIADO" NUMBER NOT NULL ENABLE, 
	"TIPO" VARCHAR2(20 BYTE), 
	"NUMERO" VARCHAR2(20 BYTE), 
	"PERSONA_EMERGENCIA" VARCHAR2(100 BYTE), 
	"RELACION_PERSONA_EMERGENCIA" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."TELEFONO" ADD PRIMARY KEY ("ID_TELEFONO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."TELEFONO" ADD CONSTRAINT "CHK_TELEFONO_TIPO" CHECK (tipo IN ('casa','cel','trabajo','emergencia')) ENABLE;
ALTER TABLE "ADMIN"."TELEFONO" ADD CONSTRAINT "FK_TELEFONO_ASOCIADO" FOREIGN KEY ("ID_ASOCIADO")
	  REFERENCES "ADMIN"."ASOCIADO" ("ID_ASOCIADO") ENABLE;

-- HISTORIAL_MEDICO
CREATE TABLE "ADMIN"."HISTORIAL_MEDICO" 
   (	"ID_HISTORIAL" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_ASOCIADO" NUMBER NOT NULL ENABLE, 
	"LUGAR_NACIMIENTO" VARCHAR2(150 BYTE), 
	"HOSPITAL" VARCHAR2(150 BYTE), 
	"TIPO_SANGRE" VARCHAR2(5 BYTE), 
	"TIENE_VALVULA" NUMBER(1,0), 
	"NOTAS" CLOB, 
	"ALERGIAS" CLOB, 
	"FECHA_NACIMIENTO" TIMESTAMP (6), 
	"SEXO" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("NOTAS") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ALERGIAS") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
ALTER TABLE "ADMIN"."HISTORIAL_MEDICO" ADD CHECK (tiene_valvula IN (0,1)) ENABLE;
ALTER TABLE "ADMIN"."HISTORIAL_MEDICO" ADD PRIMARY KEY ("ID_HISTORIAL")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."HISTORIAL_MEDICO" ADD UNIQUE ("ID_ASOCIADO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."HISTORIAL_MEDICO" ADD CONSTRAINT "CHK_ASC_SEX" CHECK (sexo in ('Masculino','Femenino')) ENABLE;
ALTER TABLE "ADMIN"."HISTORIAL_MEDICO" ADD CONSTRAINT "FK_HISTMED_ASOCIADO" FOREIGN KEY ("ID_ASOCIADO")
	  REFERENCES "ADMIN"."ASOCIADO" ("ID_ASOCIADO") ENABLE;

-- PADECIMIENTOS
CREATE TABLE "ADMIN"."PADECIMIENTOS" 
   (	"ID_PADECIMIENTO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(150 BYTE), 
	"DESCRIPCION" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."PADECIMIENTOS" ADD PRIMARY KEY ("ID_PADECIMIENTO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;

-- ASOCIADO_PADECIMIENTOS
CREATE TABLE "ADMIN"."ASOCIADO_PADECIMIENTO" 
   (	"ID_ASOCIADO" NUMBER NOT NULL ENABLE, 
	"ID_PADECIMIENTO" NUMBER NOT NULL ENABLE, 
	"DESCRIPCION_OTRO" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."ASOCIADO_PADECIMIENTO" ADD CONSTRAINT "PK_ASOCIADO_PADECIMIENTO" PRIMARY KEY ("ID_ASOCIADO", "ID_PADECIMIENTO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."ASOCIADO_PADECIMIENTO" ADD CONSTRAINT "FK_ASOPAD_ASOCIADO" FOREIGN KEY ("ID_ASOCIADO")
	  REFERENCES "ADMIN"."ASOCIADO" ("ID_ASOCIADO") ENABLE;
ALTER TABLE "ADMIN"."ASOCIADO_PADECIMIENTO" ADD CONSTRAINT "FK_ASOPAD_PADECIMIENTO" FOREIGN KEY ("ID_PADECIMIENTO")
	  REFERENCES "ADMIN"."PADECIMIENTOS" ("ID_PADECIMIENTO") ENABLE;

-- PADRES
CREATE TABLE "ADMIN"."PADRES" 
   (	"ID_PADRE" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_ASOCIADO" NUMBER NOT NULL ENABLE, 
	"PARENTESCO" VARCHAR2(10 BYTE), 
	"NOMBRE" VARCHAR2(150 BYTE), 
	"APELLIDO" VARCHAR2(150 BYTE), 
	"LUGAR_NACIMIENTO" VARCHAR2(150 BYTE), 
	"ESCOLARIDAD" VARCHAR2(150 BYTE), 
	"EDAD" NUMBER, 
	"OCUPACION" VARCHAR2(150 BYTE), 
	"SEGURO" VARCHAR2(150 BYTE), 
	"PARENTESCO_ENTRE_PAREJA" NUMBER(1,0), 
	"ADICCIONES" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."PADRES" ADD CHECK (parentesco_entre_pareja IN (0,1)) ENABLE;
ALTER TABLE "ADMIN"."PADRES" ADD PRIMARY KEY ("ID_PADRE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."PADRES" ADD CONSTRAINT "CHK_PADRES_PARENTESCO" CHECK (parentesco IN ('madre','padre')) ENABLE;
ALTER TABLE "ADMIN"."PADRES" ADD CONSTRAINT "FK_PADRES_ASOCIADO" FOREIGN KEY ("ID_ASOCIADO")
	  REFERENCES "ADMIN"."ASOCIADO" ("ID_ASOCIADO") ENABLE;

-- HISTORIAL_EMBARAZO
CREATE TABLE "ADMIN"."HISTORIAL_EMBARAZO" 
   (	"ID_HISTORIAL_EMB" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_PADRE" NUMBER, 
	"CIUDAD_INICIO_EMB" VARCHAR2(150 BYTE), 
	"ACIDO_FOLICO" NUMBER(1,0), 
	"CONTROL_PRENATAL" NUMBER, 
	"EXPOSICION_TOXICOS" NUMBER(1,0), 
	"DESCRIPCION_TOXICO" CLOB, 
	"OTRO_HIJO_DTN" NUMBER(1,0), 
	"FAMILIAR_DTN" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("DESCRIPCION_TOXICO") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
ALTER TABLE "ADMIN"."HISTORIAL_EMBARAZO" ADD CHECK (acido_folico IN (0,1)) ENABLE;
ALTER TABLE "ADMIN"."HISTORIAL_EMBARAZO" ADD CHECK (exposicion_toxicos IN (0,1)) ENABLE;
ALTER TABLE "ADMIN"."HISTORIAL_EMBARAZO" ADD CHECK (otro_hijo_dtn IN (0,1)) ENABLE;
ALTER TABLE "ADMIN"."HISTORIAL_EMBARAZO" ADD CHECK (familiar_dtn IN (0,1)) ENABLE;
ALTER TABLE "ADMIN"."HISTORIAL_EMBARAZO" ADD PRIMARY KEY ("ID_HISTORIAL_EMB")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."HISTORIAL_EMBARAZO" ADD UNIQUE ("ID_PADRE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."HISTORIAL_EMBARAZO" ADD CONSTRAINT "FK_HISTEMB_PADRE" FOREIGN KEY ("ID_PADRE")
	  REFERENCES "ADMIN"."PADRES" ("ID_PADRE") ENABLE;

-- CREDENCIAL
CREATE TABLE "ADMIN"."CREDENCIAL" 
   (	"ID_CREDENCIAL" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_ASOCIADO" NUMBER NOT NULL ENABLE, 
	"FOLIO" VARCHAR2(50 BYTE), 
	"FECHA_EMISION" DATE, 
	"VIGENCIA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."CREDENCIAL" ADD PRIMARY KEY ("ID_CREDENCIAL")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."CREDENCIAL" ADD UNIQUE ("ID_ASOCIADO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."CREDENCIAL" ADD UNIQUE ("FOLIO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."CREDENCIAL" ADD CONSTRAINT "FK_CREDENCIAL_ASOCIADO" FOREIGN KEY ("ID_ASOCIADO")
	  REFERENCES "ADMIN"."ASOCIADO" ("ID_ASOCIADO") ENABLE;

-- MEDICO
CREATE TABLE "ADMIN"."MEDICO" 
   (	"ID_MEDICO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(120 BYTE), 
	"ESPECIALIDAD" VARCHAR2(120 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE), 
	"CORREO" VARCHAR2(120 BYTE), 
	"CEDULA_PROFESIONAL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."MEDICO" ADD PRIMARY KEY ("ID_MEDICO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."MEDICO" ADD UNIQUE ("CORREO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."MEDICO" ADD UNIQUE ("CEDULA_PROFESIONAL")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;

-- TIPO_ESTUDIO
CREATE TABLE "ADMIN"."TIPO_ESTUDIO" 
   (	"ID_TIPO_ESTUDIO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(150 BYTE), 
	"DESCRIPCION" VARCHAR2(200 BYTE), 
	"TIEMPO_PREPARACION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."TIPO_ESTUDIO" ADD PRIMARY KEY ("ID_TIPO_ESTUDIO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;

-- ESTUDIO
CREATE TABLE "ADMIN"."ESTUDIO" 
   (	"ID_ESTUDIO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_ASOCIADO" NUMBER NOT NULL ENABLE, 
	"ID_MEDICO" NUMBER, 
	"ID_TIPO_ESTUDIO" NUMBER, 
	"LABORATORIO" VARCHAR2(150 BYTE), 
	"FECHA" TIMESTAMP (6), 
	"APORTACION" NUMBER(10,2), 
	"YA_APORTO" NUMBER(1,0), 
	"FECHA_CITA" TIMESTAMP (6), 
	"ESTATUS" VARCHAR2(50 BYTE), 
	"RESULTADOS" CLOB, 
	"ID_CONSULTA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("RESULTADOS") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
ALTER TABLE "ADMIN"."ESTUDIO" ADD CHECK (ya_aporto IN (0,1)) ENABLE;
ALTER TABLE "ADMIN"."ESTUDIO" ADD PRIMARY KEY ("ID_ESTUDIO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."ESTUDIO" ADD CONSTRAINT "CHK_ESTUDIO_ESTATUS" CHECK (estatus IN ('Pendiente','En proceso','Completado','Cancelado')) ENABLE;
ALTER TABLE "ADMIN"."ESTUDIO" ADD CONSTRAINT "FK_ESTUDIO_ASOCIADO" FOREIGN KEY ("ID_ASOCIADO")
	  REFERENCES "ADMIN"."ASOCIADO" ("ID_ASOCIADO") ENABLE;
ALTER TABLE "ADMIN"."ESTUDIO" ADD CONSTRAINT "FK_ESTUDIO_MEDICO" FOREIGN KEY ("ID_MEDICO")
	  REFERENCES "ADMIN"."MEDICO" ("ID_MEDICO") ENABLE;
ALTER TABLE "ADMIN"."ESTUDIO" ADD CONSTRAINT "FK_ESTUDIO_TIPO_ESTUDIO" FOREIGN KEY ("ID_TIPO_ESTUDIO")
	  REFERENCES "ADMIN"."TIPO_ESTUDIO" ("ID_TIPO_ESTUDIO") ENABLE;
ALTER TABLE "ADMIN"."ESTUDIO" ADD CONSTRAINT "FK_ESTUDIO_CONSULTA" FOREIGN KEY ("ID_CONSULTA")
	  REFERENCES "ADMIN"."CONSULTA" ("ID_CONSULTA") ENABLE;

-- RECIBO
CREATE TABLE "ADMIN"."RECIBO" 
   (	"ID_RECIBO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_ASOCIADO" NUMBER NOT NULL ENABLE, 
	"ID_USUARIO" NUMBER, 
	"FOLIO" VARCHAR2(50 BYTE), 
	"FECHA" DATE NOT NULL ENABLE, 
	"FECHA_LIMITE" DATE, 
	"TIPO_ZONA" VARCHAR2(10 BYTE), 
	"TIPO_CUOTA" VARCHAR2(10 BYTE), 
	"TOTAL" NUMBER(10,2), 
	"TOTAL_PAGADO" NUMBER(10,2), 
	"SALDO_PENDIENTE" NUMBER(10,2), 
	"ESTATUS" VARCHAR2(20 BYTE), 
	"NOTA" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("NOTA") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
ALTER TABLE "ADMIN"."RECIBO" ADD PRIMARY KEY ("ID_RECIBO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."RECIBO" ADD UNIQUE ("FOLIO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."RECIBO" ADD CONSTRAINT "CHK_RECIBO_ZONA" CHECK (tipo_zona IN ('urbano','rural')) ENABLE;
ALTER TABLE "ADMIN"."RECIBO" ADD CONSTRAINT "CHK_RECIBO_CUOTA" CHECK (tipo_cuota IN ('exento','cuota')) ENABLE;
ALTER TABLE "ADMIN"."RECIBO" ADD CONSTRAINT "CHK_RECIBO_ESTATUS" CHECK (estatus IN ('pagado','parcial','no_pagado')) ENABLE;
ALTER TABLE "ADMIN"."RECIBO" ADD CONSTRAINT "FK_RECIBO_ASOCIADO" FOREIGN KEY ("ID_ASOCIADO")
	  REFERENCES "ADMIN"."ASOCIADO" ("ID_ASOCIADO") ENABLE;
ALTER TABLE "ADMIN"."RECIBO" ADD CONSTRAINT "FK_RECIBO_USUARIO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "ADMIN"."USUARIOS" ("ID_USUARIO") ENABLE;

-- CONSULTA
CREATE TABLE "ADMIN"."CONSULTA" 
   (	"ID_CONSULTA" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_ASOCIADO" NUMBER NOT NULL ENABLE, 
	"ID_MEDICO" NUMBER, 
	"ID_RECIBO" NUMBER, 
	"FECHA" TIMESTAMP (6), 
	"TIPO_CONSULTA" VARCHAR2(20 BYTE), 
	"MOTIVO" CLOB, 
	"DIAGNOSTICO" CLOB, 
	"TRATAMIENTO" CLOB, 
	"APORTACION" NUMBER(10,2), 
	"YA_APORTO" NUMBER(1,0), 
	"ESTATUS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("MOTIVO") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("DIAGNOSTICO") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("TRATAMIENTO") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
ALTER TABLE "ADMIN"."CONSULTA" ADD CHECK (ya_aporto IN (0,1)) ENABLE;
ALTER TABLE "ADMIN"."CONSULTA" ADD PRIMARY KEY ("ID_CONSULTA")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."CONSULTA" ADD CONSTRAINT "CHK_CONSULTA_TIPO" CHECK (tipo_consulta IN ('primera','seguimiento')) ENABLE;
ALTER TABLE "ADMIN"."CONSULTA" ADD CONSTRAINT "CHK_ESTATUS_CONSULTA" CHECK (estatus in ('Pendiente' , 'En proceso' , 'Completado' , 'Cancelado')) ENABLE;
ALTER TABLE "ADMIN"."CONSULTA" ADD CONSTRAINT "FK_CONSULTA_ASOCIADO" FOREIGN KEY ("ID_ASOCIADO")
	  REFERENCES "ADMIN"."ASOCIADO" ("ID_ASOCIADO") ENABLE;
ALTER TABLE "ADMIN"."CONSULTA" ADD CONSTRAINT "FK_CONSULTA_MEDICO" FOREIGN KEY ("ID_MEDICO")
	  REFERENCES "ADMIN"."MEDICO" ("ID_MEDICO") ENABLE;
ALTER TABLE "ADMIN"."CONSULTA" ADD CONSTRAINT "FK_CONSULTA_RECIBO" FOREIGN KEY ("ID_RECIBO")
	  REFERENCES "ADMIN"."RECIBO" ("ID_RECIBO") ENABLE;

-- ARTICULO
CREATE TABLE "ADMIN"."ARTICULO" 
   (	"ID_ARTICULO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CLAVE" VARCHAR2(50 BYTE), 
	"DESCRIPCION" VARCHAR2(200 BYTE), 
	"UNIDAD" VARCHAR2(50 BYTE), 
	"CUOTA_RECUPERACION" NUMBER(10,2), 
	"INVENTARIO_ACTUAL" NUMBER, 
	"STOCK_MINIMO" NUMBER, 
	"CATEGORIA" VARCHAR2(100 BYTE), 
	"PROVEEDOR" VARCHAR2(150 BYTE), 
	"NOMBRE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."ARTICULO" ADD PRIMARY KEY ("ID_ARTICULO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."ARTICULO" ADD UNIQUE ("CLAVE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."ARTICULO" ADD CONSTRAINT "CHK_MEDICAMENTO_TIPO" CHECK (categoria in ('medicamento', 'equipo medico', 'material medico', 'consumible')) ENABLE;

-- MOVIMIENTO_INVENTARIO
CREATE TABLE "ADMIN"."MOVIMIENTO_INVENTARIO" 
   (	"ID_MOVIMIENTO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_ARTICULO" NUMBER NOT NULL ENABLE, 
	"ID_USUARIO" NUMBER, 
	"ID_RECIBO" NUMBER, 
	"FECHA" TIMESTAMP (6), 
	"TIPO" VARCHAR2(10 BYTE), 
	"CANTIDAD" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."MOVIMIENTO_INVENTARIO" ADD PRIMARY KEY ("ID_MOVIMIENTO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."MOVIMIENTO_INVENTARIO" ADD CONSTRAINT "CHK_MOVINV_TIPO" CHECK (tipo IN ('entrada','salida')) ENABLE;
ALTER TABLE "ADMIN"."MOVIMIENTO_INVENTARIO" ADD CONSTRAINT "FK_MOVINV_ARTICULO" FOREIGN KEY ("ID_ARTICULO")
	  REFERENCES "ADMIN"."ARTICULO" ("ID_ARTICULO") ENABLE;
ALTER TABLE "ADMIN"."MOVIMIENTO_INVENTARIO" ADD CONSTRAINT "FK_MOVINV_USUARIO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "ADMIN"."USUARIOS" ("ID_USUARIO") ENABLE;
ALTER TABLE "ADMIN"."MOVIMIENTO_INVENTARIO" ADD CONSTRAINT "FK_MOVINV_RECIBO" FOREIGN KEY ("ID_RECIBO")
	  REFERENCES "ADMIN"."RECIBO" ("ID_RECIBO") ENABLE;

  CREATE TABLE "ADMIN"."COMODATO" 
   (	"ID_COMODATO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_ASOCIADO" NUMBER NOT NULL ENABLE, 
	"FECHA_ENTREGA" DATE, 
	"FECHA_DEV_ESPERADA" DATE, 
	"FECHA_DEV_REAL" DATE, 
	"ESTADO_EQUIPO" VARCHAR2(100 BYTE), 
	"NOTAS" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("NOTAS") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
ALTER TABLE "ADMIN"."COMODATO" ADD PRIMARY KEY ("ID_COMODATO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."COMODATO" ADD CONSTRAINT "FK_COMODATO_ASOCIADO" FOREIGN KEY ("ID_ASOCIADO")
	  REFERENCES "ADMIN"."ASOCIADO" ("ID_ASOCIADO") ENABLE;

-- COMODATO_DETALLE
CREATE TABLE "ADMIN"."COMODATO_DETALLE" 
   (	"ID_DETALLE" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_COMODATO" NUMBER NOT NULL ENABLE, 
	"ID_ARTICULO" NUMBER NOT NULL ENABLE, 
	"NUMERO_SERIE" VARCHAR2(100 BYTE), 
	"TIPO_USO" VARCHAR2(20 BYTE), 
	"ES_DONATIVO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."COMODATO_DETALLE" ADD CHECK (es_donativo IN (0,1)) ENABLE;
ALTER TABLE "ADMIN"."COMODATO_DETALLE" ADD PRIMARY KEY ("ID_DETALLE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."COMODATO_DETALLE" ADD CONSTRAINT "CHK_COMODET_TIPO_USO" CHECK (tipo_uso IN ('temporal','definitivo')) ENABLE;
ALTER TABLE "ADMIN"."COMODATO_DETALLE" ADD CONSTRAINT "FK_COMODET_COMODATO" FOREIGN KEY ("ID_COMODATO")
	  REFERENCES "ADMIN"."COMODATO" ("ID_COMODATO") ENABLE;
ALTER TABLE "ADMIN"."COMODATO_DETALLE" ADD CONSTRAINT "FK_COMODET_ARTICULO" FOREIGN KEY ("ID_ARTICULO")
	  REFERENCES "ADMIN"."ARTICULO" ("ID_ARTICULO") ENABLE;

-- CONCEPTO_RECIBO
CREATE TABLE "ADMIN"."CONCEPTO_RECIBO" 
   (	"ID_CONCEPTO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."CONCEPTO_RECIBO" ADD PRIMARY KEY ("ID_CONCEPTO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."CONCEPTO_RECIBO" ADD CONSTRAINT "CHK_CONCEPTO_NOMBRE" CHECK (nombre IS NOT NULL) ENABLE;

-- METODO_PAGO
CREATE TABLE "ADMIN"."METODO_PAGO" 
   (	"ID_METODO_PAGO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(50 BYTE) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."METODO_PAGO" ADD PRIMARY KEY ("ID_METODO_PAGO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."METODO_PAGO" ADD CONSTRAINT "CHK_METODO_PAGO" CHECK (nombre IN ('efectivo','tarjeta','transferencia','deposito')) ENABLE;


-- DETALLE_RECIBO
CREATE TABLE "ADMIN"."DETALLE_RECIBO" 
   (	"ID_DETALLE" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_RECIBO" NUMBER NOT NULL ENABLE, 
	"ID_ARTICULO" NUMBER, 
	"ID_CONCEPTO" NUMBER NOT NULL ENABLE, 
	"CANTIDAD" NUMBER NOT NULL ENABLE, 
	"CUOTA_UNITARIA" NUMBER(10,2) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."DETALLE_RECIBO" ADD PRIMARY KEY ("ID_DETALLE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."DETALLE_RECIBO" ADD CONSTRAINT "FK_DETRECIBO_RECIBO" FOREIGN KEY ("ID_RECIBO")
	  REFERENCES "ADMIN"."RECIBO" ("ID_RECIBO") ENABLE;
ALTER TABLE "ADMIN"."DETALLE_RECIBO" ADD CONSTRAINT "FK_DETRECIBO_ARTICULO" FOREIGN KEY ("ID_ARTICULO")
	  REFERENCES "ADMIN"."ARTICULO" ("ID_ARTICULO") ENABLE;
ALTER TABLE "ADMIN"."DETALLE_RECIBO" ADD CONSTRAINT "FK_DETRECIBO_CONCEPTO" FOREIGN KEY ("ID_CONCEPTO")
	  REFERENCES "ADMIN"."CONCEPTO_RECIBO" ("ID_CONCEPTO") ENABLE;

-- PAGO
CREATE TABLE "ADMIN"."PAGO" 
   (	"ID_PAGO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_RECIBO" NUMBER NOT NULL ENABLE, 
	"ID_METODO_PAGO" NUMBER NOT NULL ENABLE, 
	"MONTO" NUMBER(10,2) NOT NULL ENABLE, 
	"FECHA_PAGO" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."PAGO" ADD PRIMARY KEY ("ID_PAGO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."PAGO" ADD CONSTRAINT "FK_PAGO_RECIBO" FOREIGN KEY ("ID_RECIBO")
	  REFERENCES "ADMIN"."RECIBO" ("ID_RECIBO") ENABLE;
ALTER TABLE "ADMIN"."PAGO" ADD CONSTRAINT "FK_PAGO_METODO" FOREIGN KEY ("ID_METODO_PAGO")
	  REFERENCES "ADMIN"."METODO_PAGO" ("ID_METODO_PAGO") ENABLE;