CREATE ROLE superadmin;
CREATE ROLE admin_tabla;
CREATE ROLE secretaria;

--SuperAdmin Permisos
GRANT ALL ON ARTICULO TO superadmin;
GRANT ALL ON ASOCIADO TO superadmin;
GRANT ALL ON ASOCIADO_DIRECCION TO superadmin;
GRANT ALL ON ASOCIADO_PADECIMIENTO TO superadmin;
GRANT ALL ON COMODATO TO superadmin;
GRANT ALL ON COMODATO_DETALLE TO superadmin;
GRANT ALL ON CONSULTA TO superadmin;
GRANT ALL ON CREDENCIAL TO superadmin;
GRANT ALL ON DETALLE_RECIBO TO superadmin;
GRANT ALL ON DIRECCION TO superadmin;
GRANT ALL ON ESTUDIO TO superadmin;
GRANT ALL ON HISTORIAL_EMBARAZO TO superadmin;
GRANT ALL ON HISTORIAL_MEDICO TO superadmin;
GRANT ALL ON MEDICO TO superadmin;
GRANT ALL ON MOVIMIENTO_INVENTARIO TO superadmin;
GRANT ALL ON PADECIMIENTOS TO superadmin;
GRANT ALL ON PADRES TO superadmin;
GRANT ALL ON RECIBO TO superadmin;
GRANT ALL ON SOLICITUD TO superadmin;
GRANT ALL ON TELEFONO TO superadmin;
GRANT ALL ON TIPO_ESTUDIO TO superadmin;
GRANT ALL ON USUARIOS TO superadmin;    

--Admin_tabla Permisos
GRANT SELECT, INSERT, UPDATE ON USUARIOS TO admin_tabla;

GRANT SELECT, INSERT, UPDATE ON ASOCIADO TO admin_tabla;
GRANT SELECT, INSERT, UPDATE ON SOLICITUD TO admin_tabla;
GRANT SELECT, INSERT, UPDATE ON DIRECCION TO admin_tabla;
GRANT SELECT, INSERT, UPDATE ON ASOCIADO_DIRECCION TO admin_tabla;
GRANT SELECT, INSERT, UPDATE ON TELEFONO TO admin_tabla;
GRANT SELECT, INSERT, UPDATE ON HISTORIAL_MEDICO TO admin_tabla;
GRANT SELECT, INSERT, UPDATE ON PADECIMIENTOS TO admin_tabla;
GRANT SELECT, INSERT, UPDATE ON ASOCIADO_PADECIMIENTO TO admin_tabla;
GRANT SELECT, INSERT, UPDATE ON PADRES TO admin_tabla;
GRANT SELECT, INSERT, UPDATE ON HISTORIAL_EMBARAZO TO admin_tabla;
GRANT SELECT, INSERT, UPDATE ON CREDENCIAL TO admin_tabla;

GRANT SELECT, INSERT, UPDATE ON ESTUDIO TO admin_tabla;
GRANT SELECT, INSERT, UPDATE ON CONSULTA TO admin_tabla;

GRANT SELECT, INSERT, UPDATE ON RECIBO TO admin_tabla;
GRANT SELECT, INSERT, UPDATE ON DETALLE_RECIBO TO admin_tabla;

--Secretaria Permisos
GRANT SELECT, INSERT ON ASOCIADO TO secretaria;
GRANT SELECT, INSERT ON SOLICITUD TO secretaria;
GRANT SELECT, INSERT ON DIRECCION TO secretaria;
GRANT SELECT, INSERT ON ASOCIADO_DIRECCION TO secretaria;
GRANT SELECT, INSERT ON TELEFONO TO secretaria;

GRANT SELECT ON HISTORIAL_MEDICO TO secretaria;
GRANT SELECT ON PADECIMIENTOS TO secretaria;

GRANT SELECT, INSERT ON RECIBO TO secretaria;
GRANT SELECT, INSERT ON DETALLE_RECIBO TO secretaria;

GRANT SELECT ON MEDICO TO secretaria;
GRANT SELECT ON CONSULTA TO secretaria;

--Grant genral
GRANT ALL ON ADMIN.ARTICULO TO PUBLIC;
GRANT ALL ON ADMIN.ASOCIADO TO PUBLIC;
GRANT ALL ON ADMIN.ASOCIADO_DIRECCION TO PUBLIC;
GRANT ALL ON ADMIN.ASOCIADO_PADECIMIENTO TO PUBLIC;
GRANT ALL ON ADMIN.COMODATO TO PUBLIC;
GRANT ALL ON ADMIN.COMODATO_DETALLE TO PUBLIC;
GRANT ALL ON ADMIN.CONSULTA TO PUBLIC;
GRANT ALL ON ADMIN.CREDENCIAL TO PUBLIC;
GRANT ALL ON ADMIN.DBTOOLS$EXECUTION_HISTORY TO PUBLIC;
GRANT ALL ON ADMIN.DETALLE_RECIBO TO PUBLIC;
GRANT ALL ON ADMIN.DIRECCION TO PUBLIC;
GRANT ALL ON ADMIN.ESTUDIO TO PUBLIC;
GRANT ALL ON ADMIN.HISTORIAL_EMBARAZO TO PUBLIC;
GRANT ALL ON ADMIN.HISTORIAL_MEDICO TO PUBLIC;
GRANT ALL ON ADMIN.MEDICO TO PUBLIC;
GRANT ALL ON ADMIN.MOVIMIENTO_INVENTARIO TO PUBLIC;
GRANT ALL ON ADMIN.PADECIMIENTOS TO PUBLIC;
GRANT ALL ON ADMIN.PADRES TO PUBLIC;
GRANT ALL ON ADMIN.RECIBO TO PUBLIC;
GRANT ALL ON ADMIN.SOLICITUD TO PUBLIC;
GRANT ALL ON ADMIN.TELEFONO TO PUBLIC;
GRANT ALL ON ADMIN.TIPO_ESTUDIO TO PUBLIC;
GRANT ALL ON ADMIN.USUARIOS TO PUBLIC;


--Asignar roles a usuarios
--DBA Admin
CREATE USER DBAdmin_Willian IDENTIFIED BY "DBAdmin_A00840101";
GRANT SYSDBA TO DBAdmin_Willian;
GRANT superadmin TO DBAdmin_Willian;

--SuperAdmin
CREATE USER superadmin_David IDENTIFIED BY "Super_A01285837";
GRANT CREATE SESSION TO superadmin_David;
GRANT superadmin TO superadmin_David;

CREATE USER superadmin_Alex IDENTIFIED BY "Super_A01253750";
GRANT CREATE SESSION TO superadmin_Alex;
GRANT superadmin TO superadmin_Alex;

--Admin_tabla
CREATE USER admin_Marcelo IDENTIFIED BY "Admin_A01722831";
GRANT CREATE SESSION TO admin_Marcelo;
GRANT admin_tabla TO admin_Marcelo;

CREATE USER admin_Bruno IDENTIFIED BY "Admin_A01769630";
GRANT CREATE SESSION TO admin_Bruno;
GRANT admin_tabla TO admin_Bruno;

CREATE USER admin_Emi IDENTIFIED BY "Admin_A01772583";
GRANT CREATE SESSION TO admin_Emi;
GRANT admin_tabla TO admin_Emi;

--Secretaria
CREATE USER secretaria_user IDENTIFIED BY "Secretaria_123";
GRANT CREATE SESSION TO secretaria_user;
GRANT secretaria TO secretaria_user;

-- Show all system privileges granted to any user or role
SELECT * FROM DBA_SYS_PRIVS where grantee = 'ADMIN_MARCELO';
SELECT * FROM DBA_SYS_PRIVS where grantee = 'ADMIN_BRUNO';
SELECT * FROM DBA_SYS_PRIVS where grantee = 'SUPERADMIN_DAVID';

-- Show all object (table, view) privileges granted
SELECT * FROM DBA_TAB_PRIVS where grantee = 'ADMIN_MARCELO';
SELECT * FROM DBA_TAB_PRIVS where grantee = 'ADMIN_BRUNO';
SELECT * FROM DBA_TAB_PRIVS where grante = 'SUPERADMIN_DAVID';

-- Show all roles granted to users or roles
SELECT * FROM DBA_ROLE_PRIVS where GRANTED_ROLE = 'ADMIN_TABLA';
SELECT * FROM DBA_ROLE_PRIVS where GRANTED_ROLE = 'SUPERADMIN';
SELECT * FROM DBA_ROLE_PRIVS where GRANTED_ROLE = 'SECRETARIA';


